
// Airtable Configuration

// Table IDs
export const TABLES = {
  TRANSACTIONS: 'tblHyCJCpQSgjn0md',
  CLIENTS: 'tblvdy7T9Hv4SasdI'
};

// Transaction Table Field IDs
export const TRANSACTION_FIELDS = {
  MLS_NUMBER: 'fld6O2FgIXQU5G27o',
  ADDRESS: 'fldypnfnHhplWYcCW',
  PROPERTY_STATUS: 'fldV2eLxz6w0TpLFU',
  SALE_PRICE: 'fldhHjBZJISmnP8SK',
  TRANSACTION_STATUS: 'fldMplTcAn8Fl4NX8',
  WINTERIZED: 'fldExdgBDgdB1i9jy',
  UPDATE_MLS: 'fldw3GlfvKtyNfIAW',
  COMMISSION_BASE: 'fldwx7zlKIGGIAxfq',
  SELLERS_ASSIST: 'fldTvXx96Na0zRh6W',
  TOTAL_COMMISSION: 'fldsOqVJDGYKUjD8L',
  TOTAL_COMMISSION_PERCENTAGE: 'fldE8INzEorBtx2uN',
  FIXED_COMMISSION_AMOUNT: 'fldNXNV9Yx2LwJPhN',
  LISTING_AGENT_PERCENTAGE: 'flduuQQT7o6XAGlRe',
  BUYERS_AGENT_PERCENTAGE: 'fld5KRrToAAt5kOLd',
  BUYER_PAID_PERCENTAGE: 'flddRltdGj05Clzpa',
  REFERRAL: 'fldLVyXkhqppQ7WpC',
  REFERRAL_PARTY: 'fldzVtmn8uylVxuTF',
  REFERRAL_FEE: 'fldewmjoaJVwiMF46',
  SPECIAL_INSTRUCTIONS: 'fldDWN8jU4kdCffzu',
  URGENT_ISSUES: 'fldgW16aPdFMdspO6',
  ADDITIONAL_INFORMATION: 'fld30htJ7euVerCLW',
  REQUIRES_FOLLOW_UP: 'fldIG7LFmo1Sro6Oz',
  CLIENTS: 'fldmPyBwuOO1dgj1g',
  AGENT_NAME: 'fldFD4xHD0vxnSOHJ',
  DATE_SUBMITTED: 'fldSSndzSwwzeLSph',
  TERMS_ACCEPTED: 'fldgBdQYZLx6IRdSn',
  INFO_CONFIRMED: 'fldlFelkiiGDrSCqe',
  TASKS: 'fldkprQrXSuN7CYeA',
  REPORTS_TRANSACTION_PROGRESS: 'fldQT0vtCDQ8WDAjA',
  REPORTS_COMMISSION_DETAILS: 'fldqq2KzTLzVjUPf8',
  VIEWS: 'fld0An8waRWm0CO3a',
  AUTOMATIONS: 'fldFAX233JvBfTOKG',
  REMINDERS: 'fldXCUEudmBdS1W3q',
  CHECKLISTS: 'flddPbEJRSgkGwqex',
  DOCUMENTS: 'fldNIkOPi3mBJGNMZ',
  INTEGRATIONS: 'fldeAgU8of89YQx1J',
  BROKER_EIN: 'fld20VbKbWzdR4Sp7',
  AGENT_ROLE: 'fldOVyoxz38rWwAFy',
  END_DATE: 'fldw79mq3CuOF9ksI',
  AGENTS: 'fldzoxd0wLiLfVDwO',
  EMAIL_TO: 'fldTfF9mx2JGOPh2y',
  EMAIL_CC: 'fldFjBa6Kc2p5Q4VB'
};

// Client Table Field IDs
export const CLIENT_FIELDS = {
  CLIENT_NAME: 'fldSqxNOZ9B5PgSab',
  CLIENT_EMAIL: 'flddP6a8EG6qTJdIi',
  CLIENT_PHONE: 'fldBnh8W6iGW014yY',
  CLIENT_ADDRESS: 'fldz1IpeR1256LhuC',
  CLIENT_TYPE: 'fldSY6vbE1zAhJZqd',
  MARITAL_STATUS: 'fldeK6mjSfxELU0MD',
  CLIENT_INDEX: 'fldKzrdhld2YmPGLN',
  TRANSACTIONS: 'fldYsIpMRHmvRjpUd',
  REPORTS: 'fld9V6iCO99MQ1WiE',
  VIEWS: 'fld6a1Dg4PZ1Vz79V',
  AUTOMATIONS: 'fldTfOSCBrN5Z8zpS',
  REMINDERS: 'fldf2NiyrfTUqpf1R',
  CHECKLISTS: 'fldYIcr5GE2KVoltR'
};
